### ISSUE TITLE
Is there any pattern to videos that will not produce a filmstrip or thumbnails?

### ISSUE THREAD

**Issue by StinkySunshine** [whyboris/Video-Hub-App#793]
I've been working with a large volume of video files and frequently get videos that do not produce a filmstrip or thumbnails as shown in the below image

![image](https://user-images.githubusercontent.com/58363026/218633044-9aacc556-850e-418a-90d5-0a47063f061e.png)

I purchased this product specifically so I could look at a filmstrip of lots of videos at once to vet them very fast and this is by far the best product i've found for it. I appreciate the hard work and I'm not expecting it to work for every video. If there is any pattern as to what videos will black out like this I could use a script to segregate them. Do you know if there's any pattern to videos that get blacked out?

**Comment by whyboris** [comment]
I have a few guesses about why some videos do not have screenshots:
- Firstly, it's best to not have any other software running when generating screenshots
- There could be a bug in my code when computing [extraction duration timeout](https://github.com/whyboris/Video-Hub-App/blob/main/node/main-extract.ts#L397) -- perhaps it's too short for the hardware or for the task at hand
- There may be an unsupported _codec_
- File is corrupt in some way (which may still make it _playable_ in a video player, but the corruption could prevent extraction of screenshots). A common corruption is not a fully-downloaded video (a torrent for example that has only parts of the file with actual data).

In your case, specific for this video, I see the length is 7 seconds (and it comes from _Tumblr_ which might have a weird codec). Perhaps short videos are particularly tricky to extract screenshots for (I'm unsure).

You _could_ try doing science on your own (copy a few files for which no screenshots are generated to a folder, try to create a hub from that folder -- varying the settings of number of screenshots and screenshot size) - but that's not _needed_ -- only if you feel like you'll have a good time doing it.

I'm hoping to release a bugfix version on February 20th (5th anniversary of the app 🥳 ) which should have a newer version of _FFmpeg_ -- which does the screenshot extraction; maybe it will help 🤞

**Comment by whyboris** [comment]
@StinkySunshine - Have you tried the version `3.2.0` that I just released? It has a new _FFmpeg_ and may fix your problem 🤞

**Comment by ArchSimon** [comment]
This issue still persists it seems.  I have tried isolating the videos that failed to generate thumbs in a large catalog, into a separate folder, and get just seemingly random results. Some generate neither filmstrip or thumbnail, others just the filmstrip and no thumbnail in which case you can see scenes when moving the mouse over the clip, but it still shows a black thumbnail in the catalog.

I made several catalogues of a folder with about 12 GoPro videos. Each time the catalog built, a different set of videos failed to generate their thumbnails and / or filmstrips.

![Image](https://github.com/user-attachments/assets/57597b67-8ec6-4fc5-9540-3137cbcb1aa3)

![Image](https://github.com/user-attachments/assets/c186132f-9e5e-414d-a35a-6c904db99d69)
